### ISSUE TITLE
 bodhi-client-0.9.12.2-6.fc25 requires koji-1.10

### ISSUE THREAD

**Issue by tkdchen** [fedora-infra/bodhi#1743]
bodhi-client-0.9.12.2-6.fc25.noarch requires koji-1.10, which blocks to release new versions of rpkg and fedpkg because rpkg has been migrated to require python2-koji-1.13 and in the meantime bodhi-client is required by fedpkg.

**Comment by bowlofeggs** [comment]
Hello @tkdchen!

The Bodhi spec file doesn't put a version requirement on koji:

```
$ rpm -q --requires bodhi-client
/usr/bin/python2
koji
python-fedora >= 0.3.5
python-kitchen
python2-dnf
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
yum
```

Did you find that the bodhi-0.9 client fails to function with koji-1.13 in some way? Could you describe the problem?

**Comment by tkdchen** [comment]
@bowlofeggs Hi,

> The Bodhi spec file doesn't put a version requirement on koji:

This is why I'm confused. I'm testing new version rpkg-1.50, which requires python2-koji, and fedpkg-1.29. When installing both of them, ``bodhi-client-0.9.12.2-6.fc25`` is resolved to be installed, and ``koji-1.10`` is also resolved as a dependency to be installed eventually. That causes the whole installation fails due to the conflict between ``python2-koji`` and ``koji-1.10``.

Reproduce steps, using Fedora 25 docker container,

```
docker run --rm -i -t fedora:25 /bin/bash
[root@b56e4b783654 /]# dnf install -y bodhi-client
Fedora 25 - x86_64 - Updates                                                                                       3.6 MB/s |  25 MB     00:06    
Last metadata expiration check: 0:00:12 ago on Fri Aug 11 15:10:56 2017.
Dependencies resolved.
===================================================================================================================================================
 Package                                  Arch                     Version                                         Repository                 Size
===================================================================================================================================================
Installing:
 bodhi-client                             noarch                   0.9.12.2-6.fc25                                 updates                    26 k
 cpio                                     x86_64                   2.12-3.fc24                                     fedora                    261 k
 gc                                       x86_64                   7.4.4-1.fc25                                    fedora                    104 k
 guile                                    x86_64                   5:2.0.13-1.fc25                                 fedora                    3.5 M
 koji                                     noarch                   1.10.1-13.fc25                                  fedora                    279 k
 libatomic_ops                            x86_64                   7.4.4-1.fc25                                    fedora                     32 k
 libstdc++                                x86_64                   6.4.1-1.fc25                                    updates                   459 k
 libtool-ltdl                             x86_64                   2.4.6-14.fc25                                   updates                    54 k
 libxslt                                  x86_64                   1.1.28-13.fc25                                  fedora                    247 k
 make                                     x86_64                   1:4.1-6.fc25                                    updates                   468 k
 openssl                                  x86_64                   1:1.0.2j-1.fc25                                 fedora                    492 k
......
[root@b56e4b783654 /]# rpm -q bodhi-client koji
bodhi-client-0.9.12.2-6.fc25.noarch
koji-1.10.1-13.fc25.noarch
```

I see ``python2-koji`` instead of ``koji`` has been a dependency for >=f25 packages in spec file https://src.fedoraproject.org/rpms/bodhi/blob/master/f/bodhi.spec#_49, however bodhi-client is still an old version in current Fedora 25 repo.

**Comment by tkdchen** [comment]
There is a f25 build https://koji.fedoraproject.org/koji/buildinfo?buildID=947163, maybe it needs to be pushed to Fedora 25 repository in a new bodhi update?

**Comment by tkdchen** [comment]
``bodhi-2.9.0-1.fc25`` looks doesn't work as well. 

```
docker run --rm -i -t fedora:25 /bin/bash
[root@6109c0874daa /]# dnf install https://kojipkgs.fedoraproject.org//packages/bodhi/2.9.0/1.fc25/noarch/bodhi-client-2.9.0-1.fc25.noarch.rpm https://kojipkgs.fedoraproject.org//packages/bodhi/2.9.0/1.fc25/noarch/python2-bodhi-2.9.0-1.fc25.noarch.rpm
Fedora 25 - x86_64                                                                                                 4.7 MB/s |  50 MB     00:10    
Fedora 25 - x86_64 - Updates                                                                                       4.0 MB/s |  25 MB     00:06    
Last metadata expiration check: 0:00:10 ago on Fri Aug 11 16:03:08 2017.
Dependencies resolved.
===================================================================================================================================================
 Package                                 Arch                    Version                                       Repository                     Size
===================================================================================================================================================
Installing:
 bodhi-client                            noarch                  2.9.0-1.fc25                                  @commandline                   58 k
 cpio                                    x86_64                  2.12-3.fc24                                   fedora                        261 k
 gc                                      x86_64                  7.4.4-1.fc25                                  fedora                        104 k
 guile                                   x86_64                  5:2.0.13-1.fc25                               fedora                        3.5 M
 koji                                    noarch                  1.10.1-13.fc25                                fedora                        279 k
 libatomic_ops                           x86_64                  7.4.4-1.fc25                                  fedora                         32 k
 libstdc++                               x86_64                  6.4.1-1.fc25                                  updates                       459 k
```

```
[root@6109c0874daa /]# rpm -q koji bodhi-client
koji-1.10.1-13.fc25.noarch
bodhi-client-2.9.0-1.fc25.noarch
[root@6109c0874daa /]# rpm -q --requires bodhi-client
/usr/bin/python2
bash-completion
koji
python(abi) = 2.7
python-click
python-dnf
python-fedora >= 0.9
python2-bodhi = 2.9.0-1.fc25
python2-six
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PartialHardlinkSets) <= 4.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
```

**Comment by tkdchen** [comment]
Just rebuilt ``bodhi-2.9.0-4`` f25 packages locally and tried to install ``bodhi-client`` in f25 and f26 container individually. A strange thing is, in f26, ``koji-1.13`` can be resolved, but in f25 ``koji-1.10`` is found to be installed along with ``bodhi-client``. Something wrong with koji in Fedora repos?

**Comment by bowlofeggs** [comment]
@tkdchen Hello again!

The F25 build of Bodhi 2 is not intended to be released to F25 - that was done simply in order to be tagged into the infra repository. Bodhi 2 is not backwards compatible with Bodhi 0.9.

However, I am still not sure that Bodhi is what is pulling in Koji 1.10, specifically. It does pull in koji, but without specifying a version as far as I can tell.

This could be a koji packaging issue, or perhaps something else that is installed on your system is specifically requiring koji-1.10? I am able to install bodhi-client on an F25 VM that I have with no issues.

**Comment by tkdchen** [comment]
@bowlofeggs thanks for your reply. I found this should not be caused by bodhi package. I sent a mail to devel mailing list to describe the problem. I'll close this issue.
